### ISSUE TITLE
ValueError: could not convert string to float: '0.12.2'

### ISSUE THREAD

**Issue by chuong98** [NoiSek/Flask-MicroServices#1]
Executing:  `python app.py` returning error:
`Traceback (most recent call last):
  File "app.py", line 1, in <module> from ExampleApp import app

  File "/home/flask-microservice-example/ExampleApp/__init__.py", line 1, in <module>
    from flask_microservices import MicroServicesApp

  File "/home/xxx/anaconda3/lib/python3.6/site-packages/flask_microservices/__init__.py", line 22, in <module>
    FLASK_VERSION = float(__version__)
ValueError: could not convert string to float: '0.12.2'
`

**Comment by hmanjarawala** [comment]
Hi,
I am also getting same issue.

**ValueError**: could not convert string to float: '1.0.2'

**Comment by ilulillirillion** [comment]
I ran into the same with version 1.1.2. I created a pull request to fix https://github.com/NoiSek/Flask-MicroServices/pull/3

A work around until then is:
```
import flask
flask.__version__ = 1.1
from flask_microservices import MicroServicesApp
```

Set the __version__ attribute of flask to whatever the closest relative major version would be for what you have, so 1.0.2 would be 1.0

There may be a better workaround that's just something to try and help, I have no idea if modifying that number in that way will cause other problems but I'm sure there are issues one could run into arbitrarily modifying it.
